### ISSUE TITLE
TINKER.log characters

### ISSUE THREAD

**Issue by elwait** [bdw2292/AMOEBAAnnihilator#10]
superscript characters (encoded with UTF-8) printed to TINKER.log for BAR calculation results are not displayed properly on nova

Example:
`/home/eew947/MELK_IN17_rep/AA_input/TINKER.log`

> Fri Apr  9 15:34:15 2021 ΔGᶜᵒᵐᵖᵘⁿᶜᵒʳʳ = -0.8607
> Fri Apr  9 15:34:15 2021 ΔGᶜᵒᵐᵖᶜᵒʳʳᵉʳʳ = 0.0062
> Fri Apr  9 15:34:15 2021 ΔHᶜᵒᵐᵖ = 0.3664
> Fri Apr  9 15:34:15 2021 ΔHᶜᵒᵐᵖᵉʳʳ = 0.0
> Fri Apr  9 15:34:15 2021 ΔSᶜᵒᵐᵖ = 0.00409
> Fri Apr  9 15:34:15 2021 ΔSᶜᵒᵐᵖᵉʳʳ = 0.0

![image](https://user-images.githubusercontent.com/51386555/114578665-b5fd8f00-9c42-11eb-9bba-b52952cc9a10.png)

**Comment by bdw2292** [comment]
![Capture](https://user-images.githubusercontent.com/43654521/115056011-e7c35f80-9ea7-11eb-958d-1a9124a1f471.PNG)
![Capture2](https://user-images.githubusercontent.com/43654521/115056012-e8f48c80-9ea7-11eb-89e0-7c6607a77fd3.PNG)
I am unable to reproduce this, it looks fine to me with vi and less on nova.
