### ISSUE TITLE
Collect calculated free energy for each step and free energy via forward and backward FEP for comparison

### ISSUE THREAD

**Issue by elwait** [bdw2292/AMOEBAAnnihilator#11]
Collect the following results for each step into one file in the main directory.

Free Energy via BAR Iteration
Free Energy via BAR Bootstrap
Free Energy via Forward FEP  
Free Energy via Backward FEP 

This would be useful for troubleshooting (more steps necessary?)

**Comment by bdw2292** [comment]
Fixed
