### ISSUE TITLE
Files for Visualization in Pymol

### ISSUE THREAD

**Issue by elwait** [bdw2292/AMOEBAAnnihilator#5]
Pymol is not reading the complexed file outputs properly. Would be nice to automatically generate a file that Pymol can properly read for each stucture

![image](https://user-images.githubusercontent.com/51386555/107800860-f44efe80-6d24-11eb-8212-7be29c41935c.png)

**Comment by bdw2292** [comment]
If _pymol.xyz in name, then it is pymol readable now. Mentioned in manifest readme.
